In [2]:
import numpy as np
import pandas as pd

In [3]:
census_data = pd.read_csv("Data/Census_data.dbf.csv", index_col = False)
cancer_data = pd.read_excel("Data/Prostate_C_2015-2019.xlsx")

In [4]:
print(census_data)
print(cancer_data)

    STATEFP20  COUNTYFP20  COUNTYNS20  GEOID20      NAME20         NAMELSAD20  \
0          41           9     1135847    41009    Columbia    Columbia County
1          41          27     1155131    41027  Hood River  Hood River County
2          41          25     1135852    41025      Harney      Harney County
3          41          41     1135856    41041     Lincoln     Lincoln County
4          41          33     1155133    41033   Josephine   Josephine County
..        ...         ...         ...      ...         ...                ...
70         53          47     1531928    53047    Okanogan    Okanogan County
71         53          63     1529225    53063     Spokane     Spokane County
72         53          29     1513272    53029      Island      Island County
73         53           9     1531341    53009     Clallam     Clallam County
74         53          65     1531930    53065     Stevens     Stevens County

    LSAD20 CLASSFP20 MTFCC20  CSAFP20  ...  GQESTIMATE  GQESTIMA_1 GQESTIMA_2  \
0        6        H1   G4020    440.0  ...         369         369        369
1        6        H1   G4020      NaN  ...         773         773        773
2        6        H1   G4020      NaN  ...         150         150        150
3        6        H1   G4020      NaN  ...         786         786        786
4        6        H1   G4020    366.0  ...        1520        1520       1520
..     ...       ...     ...      ...  ...         ...         ...        ...
70       6        H1   G4020      NaN  ...         504         504        504
71       6        H1   G4020    518.0  ...       14355       14355      14355
72       6        H1   G4020    500.0  ...        1933        1933       1933
73       6        H1   G4020      NaN  ...        1668        1668       1668
74       6        H1   G4020    518.0  ...         214         214        214

    RBIRTH2021  RDEATH2021  RNATURALCH  RINTERNATI  RDOMESTICM  RNETMIG202  \
0     9.119720   11.295587   -2.175867   -0.113523   10.709049   10.595525
1     9.666667    8.416667    1.250000    0.125000    3.250000    3.375000
2     9.425196   13.274924   -3.849728    0.000000   15.000664   15.000664
3     7.282847   15.039375   -7.756528    0.118420   15.453846   15.572266
4     8.478274   16.355815   -7.877541    0.045338   10.609178   10.654516
..         ...         ...         ...         ...         ...         ...
70    9.958467   13.097036   -3.138569    1.132717   14.229753   15.362469
71   10.138580   10.677807   -0.539227    0.207961   10.105453   10.313414
72    9.072141   10.379631   -1.307489    0.183507    6.743893    6.927400
73    7.396022   15.782467   -8.386445    0.450193   20.142904   20.593097
74    7.915567   12.894714   -4.979147    0.063835   23.555196   23.619031

    StCty_1
0   41009.0
1   41027.0
2   41025.0
3   41041.0
4   41033.0
..      ...
70  53047.0
71  53063.0
72  53029.0
73  53009.0
74  53065.0

[75 rows x 57 columns]
      WA State Cancer Registry (WSCR) Web Application  \
0                                  Results generated:
1                                                 NaN
2                                         Cancer Site
3                                            Prostate
4                                                 NaN
5                                           Data Type
6                                           Incidence
7                                           Incidence
8                                           Incidence
9                                           Incidence
10                                          Incidence
11                                          Incidence
12                                          Incidence
13                                          Incidence
14                                          Incidence
15                                          Incidence
16                                          Incidence
17                                          Incidence
18                                          Incidence
19                                          Incidence
20                                          Incidence
21                                          Incidence
22                                          Incidence
23                                          Incidence
24                                          Incidence
25                                          Incidence
26                                          Incidence
27                                          Incidence
28                                          Incidence
29                                          Incidence
30                                          Incidence
31                                          Incidence
32                                          Incidence
33                                          Incidence
34                                          Incidence
35                                          Incidence
36                                          Incidence
37                                          Incidence
38                                          Incidence
39                                          Incidence
40                                          Incidence
41                                          Incidence
42                                          Incidence
43                                          Incidence
44                                          Incidence
45                                                NaN
46                                                NaN
47                                                NaN
48  Washington State Cancer Incidence Data: Washin...

                         https://fortress.wa.gov/wscr    Unnamed: 2  \
0        May 8, 2023 6:47:06 PM Pacific Daylight Time           NaN
1                                                 NaN           NaN
2                             Incidence Codes ICD-0-3           NaN
3   C61.9, excluding histology codes 9140, 9050-90...           NaN
4                                                 NaN           NaN
5                                         Cancer Site     Geography
6                                            Prostate         Adams
7                                            Prostate        Asotin
8                                            Prostate        Benton
9                                            Prostate        Chelan
10                                           Prostate       Clallam
11                                           Prostate         Clark
12                                           Prostate      Columbia
13                                           Prostate       Cowlitz
14                                           Prostate       Douglas
15                                           Prostate         Ferry
16                                           Prostate      Franklin
17                                           Prostate      Garfield
18                                           Prostate         Grant
19                                           Prostate  Grays Harbor
20                                           Prostate        Island
21                                           Prostate     Jefferson
22                                           Prostate          King
23                                           Prostate        Kitsap
24                                           Prostate      Kittitas
25                                           Prostate     Klickitat
26                                           Prostate         Lewis
27                                           Prostate       Lincoln
28                                           Prostate         Mason
29                                           Prostate      Okanogan
30                                           Prostate       Pacific
31                                           Prostate  Pend Oreille
32                                           Prostate        Pierce
33                                           Prostate      San Juan
34                                           Prostate        Skagit
35                                           Prostate      Skamania
36                                           Prostate     Snohomish
37                                           Prostate       Spokane
38                                           Prostate       Stevens
39                                           Prostate      Thurston
40                                           Prostate     Wahkiakum
41                                           Prostate   Walla Walla
42                                           Prostate       Whatcom
43                                           Prostate       Whitman
44                                           Prostate        Yakima
45                                                NaN           NaN
46                                                NaN           NaN
47                                                NaN           NaN
48                                                NaN           NaN

   Unnamed: 3 Unnamed: 4 Unnamed: 5 Unnamed: 6                 Unnamed: 7  \
0         NaN        NaN        NaN        NaN                        NaN
1         NaN        NaN        NaN        NaN                        NaN
2         NaN        NaN        NaN        NaN                        NaN
3         NaN        NaN        NaN        NaN                        NaN
4         NaN        NaN        NaN        NaN                        NaN
5        Year  Age Group     Gender       Race  Average Annual Population
6   2015-2019        All       Male        All                      10052
7   2015-2019        All       Male        All                      10954
8   2015-2019        All       Male        All                      97565
9   2015-2019        All       Male        All                      38350
10  2015-2019        All       Male        All                      37020
11  2015-2019        All       Male        All                     232361
12  2015-2019        All       Male        All                       2066
13  2015-2019        All       Male        All                      52527
14  2015-2019        All       Male        All                      20833
15  2015-2019        All       Male        All                       4045
16  2015-2019        All       Male        All                      46682
17  2015-2019        All       Male        All                       1080
18  2015-2019        All       Male        All                      49027
19  2015-2019        All       Male        All                      38084
20  2015-2019        All       Male        All                      40855
21  2015-2019        All       Male        All                      15589
22  2015-2019        All       Male        All                    1072340
23  2015-2019        All       Male        All                     133730
24  2015-2019        All       Male        All                      22869
25  2015-2019        All       Male        All                      10985
26  2015-2019        All       Male        All                      39117
27  2015-2019        All       Male        All                       5401
28  2015-2019        All       Male        All                      32680
29  2015-2019        All       Male        All                      21460
30  2015-2019        All       Male        All                      10854
31  2015-2019        All       Male        All                       6853
32  2015-2019        All       Male        All                     423375
33  2015-2019        All       Male        All                       8062
34  2015-2019        All       Male        All                      61832
35  2015-2019        All       Male        All                       5914
36  2015-2019        All       Male        All                     395381
37  2015-2019        All       Male        All                     248662
38  2015-2019        All       Male        All                      22300
39  2015-2019        All       Male        All                     135186
40  2015-2019        All       Male        All                       2012
41  2015-2019        All       Male        All                      30874
42  2015-2019        All       Male        All                     107881
43  2015-2019        All       Male        All                      24372
44  2015-2019        All       Male        All                     125942
45        NaN        NaN        NaN        NaN                        NaN
46        NaN        NaN        NaN        NaN                        NaN
47        NaN        NaN        NaN        NaN                        NaN
48        NaN        NaN        NaN        NaN                        NaN

                     Unnamed: 8                 Unnamed: 9     Unnamed: 10
0                           NaN                        NaN             NaN
1                           NaN                        NaN             NaN
2                           NaN                        NaN             NaN
3                           NaN                        NaN             NaN
4                           NaN                        NaN             NaN
5   Average Annual Observations  Age-Adj. Rate per 100,000          95% CI
6                             7                       85.5   [58.1, 123.3]
7                            10                       47.2    [35.0, 65.8]
8                           102                       85.9    [78.4, 94.1]
9                            68                      115.5  [103.2, 129.4]
10                           88                      117.5  [106.4, 130.1]
11                          189                       64.5    [60.3, 68.9]
12                            4                       74.5   [43.9, 154.1]
13                           54                       65.2    [57.6, 74.0]
14                           29                      105.2   [88.4, 124.9]
15                            3                       32.4    [16.5, 71.6]
16                           33                       85.9   [72.6, 101.3]
17                           NR                         NR              NR
18                           58                      108.9   [96.5, 122.7]
19                           71                      120.5  [108.0, 134.5]
20                           81                        107   [96.4, 119.2]
21                           53                      132.7  [116.4, 154.1]
22                         1267                      118.7  [115.7, 121.8]
23                          242                      120.8  [113.9, 128.2]
24                           25                       82.3    [68.2, 99.5]
25                           20                       95.1   [76.7, 119.4]
26                           56                       89.7   [79.3, 101.6]
27                            5                       46.5    [29.0, 79.6]
28                           65                      116.1  [103.6, 130.4]
29                           39                      102.2   [87.7, 119.6]
30                           22                      100.3   [81.0, 125.9]
31                            7                         52    [35.9, 79.8]
32                          500                      101.8   [97.7, 106.0]
33                           23                        113   [92.9, 148.6]
34                           91                       95.5   [86.7, 105.2]
35                            6                       51.5    [34.0, 84.1]
36                          472                      103.4   [99.1, 107.9]
37                          171                       52.5    [49.0, 56.3]
38                           19                       43.8    [34.9, 55.8]
39                          187                      105.1   [98.3, 112.3]
40                            2                       45.5   [22.2, 162.4]
41                           40                         96   [82.9, 111.3]
42                          175                      117.3  [109.5, 125.7]
43                            5                       26.8    [17.3, 41.2]
44                          112                       81.6    [74.8, 88.9]
45                          NaN                        NaN             NaN
46                          NaN                        NaN             NaN
47                          NaN                        NaN             NaN
48                          NaN                        NaN             NaN

In [5]:
census_data.head(5)

,STATEFP20,COUNTYFP20,COUNTYNS20,GEOID20,NAME20,NAMELSAD20,LSAD20,CLASSFP20,MTFCC20,CSAFP20,...,GQESTIMATE,GQESTIMA_1,GQESTIMA_2,RBIRTH2021,RDEATH2021,RNATURALCH,RINTERNATI,RDOMESTICM,RNETMIG202,StCty_1
0,41,9,1135847,41009,Columbia,Columbia County,6,H1,G4020,440.0,...,369,369,369,9.119720,11.295587,-2.175867,-0.113523,10.709049,10.595525,41009.0
1,41,27,1155131,41027,Hood River,Hood River County,6,H1,G4020,NaN,...,773,773,773,9.666667,8.416667,1.250000,0.125000,3.250000,3.375000,41027.0
2,41,25,1135852,41025,Harney,Harney County,6,H1,G4020,NaN,...,150,150,150,9.425196,13.274924,-3.849728,0.000000,15.000664,15.000664,41025.0
3,41,41,1135856,41041,Lincoln,Lincoln County,6,H1,G4020,NaN,...,786,786,786,7.282847,15.039375,-7.756528,0.118420,15.453846,15.572266,41041.0
4,41,33,1155133,41033,Josephine,Josephine County,6,H1,G4020,366.0,...,1520,1520,1520,8.478274,16.355815,-7.877541,0.045338,10.609178,10.654516,41033.0

In [6]:
cancer_data.head(7)

,WA State Cancer Registry (WSCR) Web Application,https://fortress.wa.gov/wscr,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,Results generated:,"May 8, 2023 6:47:06 PM Pacific Daylight Time",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Cancer Site,Incidence Codes ICD-0-3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Prostate,"C61.9, excluding histology codes 9140, 9050-90...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Data Type,Cancer Site,Geography,Year,Age Group,Gender,Race,Average Annual Population,Average Annual Observations,"Age-Adj. Rate per 100,000",95% CI
6,Incidence,Prostate,Adams,2015-2019,All,Male,All,10052,7,85.5,"[58.1, 123.3]"

In [7]:
censusvcanser_data = pd.read_csv("Pop_health.csv", index_col = False)

In [8]:
print(censusvcanser_data)

      County  Data.Type Cancer.Site       State         Year  \
0      Adams  Incidence    Prostate  Washington    2014-2018
1      Adams  Mortality    Prostate  Washington    2014-2018
2     Asotin  Mortality    Prostate  Washington    2014-2018
3     Asotin  Incidence    Prostate  Washington    2014-2018
4      Baker  Mortality    Prostate      Oregon  2014 - 2018
..       ...        ...         ...         ...          ...
207  Whitman  Incidence    Prostate  Washington    2014-2018
208   Yakima  Incidence    Prostate  Washington    2014-2018
209  Yamhill  Incidence    Prostate      Oregon    2014-2018
210  Yamhill  Mortality    Prostate      Oregon  2014 - 2018
211  Yamhill  Incidence    Prostate      Oregon    2014-2018

     Average.Annual.Population  Average.Annual.Observations Column1   X  \
0                       9989.0                          6.0    85.5 NaN
1                       9989.0                          NaN     NaN NaN
2                      10880.0                          NaN     NaN NaN
3                      10880.0                         12.0    58.6 NaN
4                          NaN                         15.0    21.3 NaN
..                         ...                          ...     ...  ..
207                    24047.0                          6.0    29.8 NaN
208                   125163.0                        107.0    80.3 NaN
209                        NaN                        271.0   103.9 NaN
210                        NaN                         64.0    22.9 NaN
211                        NaN                        271.0    81.3 NaN

     OBJECTID  ...  P0040010 P0040011  P0040012  P0040028  P0040049  P0040065  \
0          53  ...        10       69        62         7         0         0
1          53  ...        10       69        62         7         0         0
2          40  ...         8      219       209         9         0         1
3          40  ...         8      219       209         9         0         1
4          24  ...         7      219       210         9         0         0
..        ...  ...       ...      ...       ...       ...       ...       ...
207        57  ...        36     1054       963        80         8         3
208        70  ...       214     2333      2208       116         6         3
209        11  ...        88     1374      1279        91         4         0
210        11  ...        88     1374      1279        91         4         0
211        11  ...        88     1374      1279        91         4         0

     P0040072 H0010001 H0010002 H0010003
0           0     6242     5720      522
1           0     6242     5720      522
2           0     9872     9236      636
3           0     9872     9236      636
4           0     8826     7040     1786
..        ...      ...      ...      ...
207         0    19323    17468     1855
208         0    85474    80592     4882
209         0    37110    34726     2384
210         0    37110    34726     2384
211         0    37110    34726     2384

[212 rows x 125 columns]

In [ ]:
censusvcanser_data.rename(columns = {'Column1' : 'Age_AdjRate_100'},